### PR TITLE
Big decimals support

### PR DESCRIPTION
**Pull request by DarkWanderer**
Big decimals support using custom type poached from public domain
Planned features:

- Feature toggle to use regular `decimal` vs new class
- Type is convertible to normal numeric types and string

TODO

- [x] Fix all inaccuracies in math operations
- [ ] Do a round of optimizations
- [x] Add config flag for supporting the new decimal
- [x] Implement parsing from text

Ref #137

### CODE REVIEW

**Comment by DmitryLk** [comment]
Hello! If I try to use ClickhouseDecimal as a Dapper parameter to Where. I get an exception "The member DecimalName of type ClickHouse.Client.Numerics.ClickHouseDecimal cannot be used as a parameter value".

        var connectionFactory = host.Services.GetService<IClickhouseConnectionFactory>()!;
        var text = @"
            SELECT *
            FROM xxxxxx.dapper_test2
            WHERE DecimalName = {DecimalName:decimal128(18)}
            ;
            ";

        var parameters = new Dictionary<string, object> { { "DecimalName", 
            new ClickHouseDecimal(BigInteger.Parse("123456789123123450000000000000"), 18)} };

        using var con = connectionFactory.GetConnection();

        var cmd = new CommandDefinition(text, parameters);
        try
        {
            var res = (await con.QueryAsync<DapperDto3>(cmd)).AsList();
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }

**Comment by DmitryLk** [comment]
Hi! Scale parameter in new ClickhouseDecimal class can be positive only (ushort). Are you planning to do it also negative to suppot such cases as {mantissa:1, scale=-3} => 1000? Thank

**Comment by DarkWanderer** [comment]
Positive-only `scale`/exponent is by design right now as it matches ClickHouse's type. I'll think about switching back to possibly-negative exponent, though

**Comment by DmitryLk** [comment]
Thanks. ClickhouseDecimal parameter with custom handler to Dapper is working

**Pull request merged**
