### PR TITLE
Added support for all column name formats

### PR DESCRIPTION
**Pull request by 2nnar**
Think, it's a bit of a flaw here in bulk insertion. I can't pass column names with backticks, for example. Moreover, it seems that passed column names are used to get absolutely the same column names without any validation, so why not to use it directly.

### CODE REVIEW

**Comment by DarkWanderer** [comment]
Hi,

The `SELECT` is done to support `COLUMNS('<regex>')` expression (although it's a rare use case), so that you can pass it as columns filter

**Comment by 2nnar** [comment]
Sure!

**Comment by 2nnar** [comment]
Well, checks are different for master and feature branches, i guess. Should I revert commit with test? So here's a code that you can run with master version. `SELECT ... LIMIT 0` works fine, but the problem is with final insert, because passed column names are overriden by the same names without backticks.
```
        [Test]
        public async Task ShouldExecuteInsertWithBacktickedColumns()
        {
            var targetTable = $"temp.backticked_columns";

            await connection.ExecuteStatementAsync($"TRUNCATE TABLE IF EXISTS {targetTable}");
            await connection.ExecuteStatementAsync($"CREATE TABLE IF NOT EXISTS {targetTable} (`field.id` Nullable(UInt8), `@value` Nullable(UInt8)) ENGINE Memory");

            using var bulkCopy = new ClickHouseBulkCopy(connection)
            {
                DestinationTableName = targetTable,
            };

            await bulkCopy.WriteToServerAsync(Enumerable.Repeat(new object[] { 5, 5 }, 5), new[] { "`field.id`, `@value`" });

            using var reader = await connection.ExecuteReaderAsync($"SELECT * FROM {targetTable}");
        }
```

**Comment by DarkWanderer** [comment]
The test set in master and PRs is usually equal, however, I've added a new test capturing the `COLUMNS(*)` case after my comment above. By merging master to your branch, you've pulled that test (and it doesn't work with your code)

I think your PR makes sense, however, columns requiring backticks are a much more common use case

**Pull request merged**
