### PR TITLE
Fix activity

### PR DESCRIPTION
**Pull request by chad122**
There is a fatal bug of the [PR - add activity](https://github.com/DarkWanderer/ClickHouse.Client/pull/289) which is i pushed several days ago.
Please merge this branch to fix it, and release a new package.

### CODE REVIEW

**Comment by DarkWanderer** [comment]
Hi,

I've merged the fix and released it. However, to prevent reoccurence - could you please add a test fixture which covers the class you added? Including the nullability cases

**Comment by chad122** [comment]
> Hi,
> 
> I've merged the fix and released it. However, to prevent reoccurence - could you please add a test fixture which covers the class you added? Including the nullability cases

ok

**Comment by chad122** [comment]
> Hi,
> 
> I've merged the fix and released it. However, to prevent reoccurence - could you please add a test fixture which covers the class you added? Including the nullability cases

I've seen your commit and i have a different idea. I think activity/trace is just an extra part. It should not throw exception to terminate the function. How about we just ignore null values instead of throw ArgumentNullException?

**Comment by DarkWanderer** [comment]
Hi. I appreciate your contribution and suggestions, however, as the code owner, I believe this is the right path to follow. You're welcome to raise PRs with changes to specific parts you think may benefit from it

**Comment by chad122** [comment]
> Hi. I appreciate your contribution and suggestions, however, as the code owner, I believe this is the right path to follow. You're welcome to raise PRs with changes to specific parts you think may benefit from it

OK

**Pull request merged**
