### PR TITLE
Add DbDataSource implementation

### PR DESCRIPTION
**Pull request by smbecker**
This PR adds a [DbDataSource](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbdatasource?view=net-8.0) implementation, which makes integration into DI containers much simpler.

### CODE REVIEW

**Comment by smbecker** [comment]
@DarkWanderer, any advice on why the "compare coverage" workflow is failing?

**Comment by DarkWanderer** [comment]
Greetings. This run unfortunately doesn't work between fork and main repo due to GitHub behavior quirk I haven't nailed down. I have disabled it in 'main' for now - checks should pass now if you rebase

P.S. I think it would be beneficial to add some tests here, even if trivial "create and call 1-2 methods"

**Comment by smbecker** [comment]
> Greetings. This run unfortunately doesn't work between fork and main repo due to GitHub behavior quirk I haven't nailed down. I have disabled it in 'main' for now - checks should pass now if you rebase

Rebased 

> P.S. I think it would be beneficial to add some tests here, even if trivial "create and call 1-2 methods"

Added a test

**Comment by DarkWanderer** [comment]
LGTM - thanks for your contribution!

It would also be beneficial to add it to `ClickHouseConnectionFactory`, so it's helpful for even more users

**Pull request merged**
